# Generated by Django 5.2.1 on 2025-05-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_views_remove_article_tags_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_markdown',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
